### PR TITLE
Feature/allow ct access

### PR DESCRIPTION
**Pull request by oleg-chemerys**
Extended functionality to also allow CT-based restriction. Added ability to override allowed content types in custom modules.

### CODE REVIEW

**Comment by d34dman** [comment]
@oleg-chemerys  along with this, we would also have to solve the confusing checkbox on node edit form for editors.

In case the force login is exempted for certain content types, then,

- either we need to replace the "checkbox" on the corresponding form with a message 
- or we could check the checkbox and make it disabled to reflect the status.

In case we have to hide the behaviour on all sites :) then it could be treated as a corner case, and the checkbox/message should be hidden via "hook_form_alter".

**Comment by oleg-chemerys** [comment]
@d34dman I think we should keep the checkbox as in most cases we need to diplay only some nodes, and adding it iinto path doesn't seem to be very user friiendly or reliable. I would leave all this options.

**Comment by d34dman** [comment]
@oleg-chemerys  sorry, i was not clear enough. Let say we have configured "article" content type in `force_login_node_type_exceptions`. Then the checkbox which would be shown on Article nodes would have no effect on the logic. This would confuse the editors.

**Comment by oleg-chemerys** [comment]
@d34dman ok, this makes sense, will hide it if something is set, coukd be tricky though.

**Comment by oleg-chemerys** [comment]
@d34dman Done, please review.

**Pull request merged**
